dataset:
  root_path: "/home/share/image_classification"
  #  name: "miniImageNet"
  name: "tiered_imagenet"
  image_size: (224, 224, 3)
  few_shot:
    n_ways: 5
    k_shots: 5
    query_shots: 15
model:
  #  load_state_dict:
  #    path: '/home/lixy/DCIRL/checkout/miniImageNet/backup/10epoch_91.38%acc.pth'
  #    start_stage: 3
  #    start_lr: 0.0005
  basic_module:
    name: 'resnet18'
    pretrained: true
    out_dim: 512
loss:
  coefficient:
    abstraction: 1
    contrast: 1
  stage_epoch_threshold: 8
train:
  batch_size: 200
  epoch: 200
  lr: 0.01
optimizer:
  # sgd, adam
  optimizer_type: "sgd"
  momentum: 0.9
  weight_decay: !!python/object/apply:eval [ 5e-4 ]
  nesterov: true
  # step, multistep, exp
  scheduler_type: "step"
  lr_decay_step: 20
  lr_decay_rate: 0.5
output:
  root_path: "/home/lixy/DCIRL/checkout"
  min_save_epoch: 1
visdom:
  env: 'dc-env'
  network:
    port: 7557
    server: 'http://localhost'
    base_url: '/'
  image_show:
    nrow: 1
    scale: 3
    height: 256
    width: 256
    number: 5
  image_win:
    origin_samples_domain: ~
    same_samples_domain: ~
    different_samples_domain: ~
  update_frequency: 10