dataset:
  name: "cat_dog"
  path: "/home/share/image_classification/cat_dog_recognition/train"
  image_size: 224
model:
  input_features: (224, 224, 3)
  basic_module:
    hidden_features: (28, 28)
    hidden_layers: 1
    out_features: (7, 28)
  middle_module:
    hidden_features: (14, 28)
    hidden_layers: 1
    out_features: (14, 14)
  senior_module:
    out_features: (784) # 28 * 28
loss:
  coefficient:
    whole_different_coefficient: 1
    off_diag_coefficient: 0.005
    common_coefficient: 1
    different_coefficient: 1
    independent_coefficient: 0.5
  threshold:
    whole_loss_threshold: 0.001
    contrast_loss_threshold: 0.001
    independent_loss_threshold: 0.001
train:
  batch_size: 10
  epoch: 50
  lr: 0.001
optimizer:
  # sgd, adam
  optimizer_type: "sgd"
  momentum: 0.9
  weight_decay: !!python/object/apply:eval [ 5e-4 ]
  nesterov: true
  # step, multistep, exp
  scheduler_type: "step"
  lr_decay_step: 40
  lr_decay_rate: 0.1
output:
  root_path: "checkout"
log:
  env: "train-env-py"
  nrow: 20
  scale: 4
  height: 256
  width: 256
  tf_logger: false
  update_frequency: 30
  accuracy_same_threshold: 0.5
  accuracy_different_threshold: -0.5