model_config:
  image_size: !!python/object/apply:eval [ 224 * 224 * 3 ]

  basic_module:
    hidden_features: !!python/object/apply:eval [ 112 * 56 ]
    hidden_layers: 3
    output_features: !!python/object/apply:eval [ 112 * 56 ]
  middle_module:
    hidden_features: !!python/object/apply:eval [ 28 * 112 ]
    hidden_layers: 2
    output_features: !!python/object/apply:eval [ 28 * 112 ]
  senior_module:
    output_features: !!python/object/apply:eval [ 112 * 112 ]

basic_config:
  batch_size: 16
  epoch: 50
  lr: &lr 0.001
  num_classes: 7

optimizer_config:
  # sgd, adam
  optimizer_type: sgd
  lr: *lr
  momentum: 0.9
  weight_decay: !!python/object/apply:eval [ 5e-4 ]
  nesterov: true

  # step, multistep, exp
  scheduler_type: step
  lr_decay_step: 40
  lr_decay_rate: 0.1
