dataset:
  name: "cat_dog"
  path: "/home/share/image_classification/cat_dog_recognition/train"
  image_size: 224
model:
  input_features: (224, 224, 3)
  basic_module:
    hidden_features: (28, 28)
    hidden_layers: 1
    out_features: (7, 28)
  middle_module:
    hidden_features: (14, 28)
    hidden_layers: 1
    out_features: (14, 14)
  senior_module:
    out_features: (784) # 28 * 28
loss:
  coefficient:
    whole_different_coefficient: 2
    common_coefficient: 1
    different_coefficient: 0.5
    independent_coefficient: 0.05
    off_diag_coefficient: 0.05
  threshold:
    whole_loss_threshold: 0.0001
    contrast_loss_threshold: 0.0001
    independent_loss_threshold: 0.0001
train:
  batch_size: 200
  epoch: 100
  lr: 0.005
optimizer:
  # sgd, adam
  optimizer_type: "sgd"
  momentum: 0.9
  weight_decay: !!python/object/apply:eval [ 5e-4 ]
  nesterov: true
  # step, multistep, exp
  scheduler_type: "step"
  lr_decay_step: 50
  lr_decay_rate: 0.1
output:
  root_path: "/home/lixy/DCIRL/checkout"
log:
  env: "train-env-py"
  nrow: 20
  scale: 4
  height: 256
  width: 256
  tf_logger: false
  update_frequency: 10
  accuracy_threshold: 0.5